/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sentimentanalysis;


import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import static sentimentanalysis.Utilities.AnalyzeText;
import static sentimentanalysis.Utilities.CalculateScore;
import static sentimentanalysis.Utilities.ClassifyScore;
import static sentimentanalysis.Utilities.accuracy;
import static sentimentanalysis.Utilities.classification;
import static sentimentanalysis.Utilities.negScore;
import static sentimentanalysis.Utilities.paging;
import static sentimentanalysis.Utilities.partOfSpeech;
import static sentimentanalysis.Utilities.posScore;
import static sentimentanalysis.Utilities.status;
import static sentimentanalysis.Utilities.termDictionary;
import static sentimentanalysis.Utilities.termIds;
import static sentimentanalysis.Utilities.tweetScore;
import static sentimentanalysis.Utilities.twitter;
import twitter4j.Status;
import twitter4j.TwitterException;

/**
 *
 * @author Chucho
 */
public class AnalyzeUser extends javax.swing.JFrame {

    /**
     * Creates new form AnalyzeUser
     */
    public AnalyzeUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblTweets = new javax.swing.JLabel();
        txtTweets = new javax.swing.JTextField();
        btnAnalyze = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResult = new javax.swing.JTextArea();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblUsername.setText("Username : ");

        txtUsername.setText("@nasa");
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });

        lblTweets.setText("Number of tweets : ");

        txtTweets.setText("1");
        txtTweets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTweetsActionPerformed(evt);
            }
        });

        btnAnalyze.setText("Analyze User");
        btnAnalyze.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalyzeActionPerformed(evt);
            }
        });

        txtResult.setEditable(false);
        txtResult.setColumns(20);
        txtResult.setRows(5);
        jScrollPane1.setViewportView(txtResult);

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUsername, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTweets, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTweets)
                            .addComponent(txtUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBack)
                            .addComponent(btnAnalyze))
                        .addGap(0, 180, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTweets)
                    .addComponent(txtTweets, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAnalyze))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void txtTweetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTweetsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTweetsActionPerformed

    private void btnAnalyzeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalyzeActionPerformed
        try {
            long startTime=System.currentTimeMillis();
            paging.setCount(Integer.parseInt(txtTweets.getText()));
            status=twitter.getUserTimeline(txtUsername.getText(), paging);
            //status = twitter.getUserTimeline(paging);
            int i=1;
            txtResult.setText("");
            for (Status st : status){
                 txtResult.append(i+":"+st.getCreatedAt()+" : "+st.getUser().getName()+" - "+ st.getText()+"\n");
                i++;
            }
            float totalScore=0;
            float totalAccuracy=0;
            for (Status st : status){
                termIds=AnalyzeText(st.getText());
                i=1;
                for (List<Integer> term : termIds)
                {
                    txtResult.append("\n"+String.valueOf(i)+".");
                    for(Integer id : term){
                        txtResult.append("Term "+termDictionary.get(id)+"("+partOfSpeech.get(id)+")" +" found with id '"+id.toString()+"'");
                        txtResult.append("\n Positive score : "+posScore.get(id));
                        txtResult.append("\n Negative score : "+negScore.get(id));
                        txtResult.append("\n Objectivity : "+String.valueOf(1-(posScore.get(id)+negScore.get(id)))+"\n");
                    }
                    i++;
                }
                tweetScore=CalculateScore(termIds);
                String result=String.valueOf(tweetScore);
                classification=ClassifyScore(tweetScore);
                txtResult.append("\n\n Tweet Score : "+result);
                txtResult.append("\n Accuracy : "+accuracy*100+"%");
                txtResult.append("\n Classified as : "+classification);
                txtResult.append("\n\n\n----------------------------------------------------------------------------------------------------------------------\n\n\n");
                totalScore=totalScore+tweetScore;
                totalAccuracy=totalAccuracy+accuracy;
            }
            totalScore=totalScore/Integer.parseInt(txtTweets.getText());
            classification=ClassifyScore(totalScore);
            totalAccuracy=totalAccuracy/Integer.parseInt(txtTweets.getText());
            txtResult.append("Total score : "+totalScore);
            txtResult.append("\nTotal Accuracy : "+totalAccuracy*100+"%");
            txtResult.append("\nClassification : "+classification);
            long endTime=System.currentTimeMillis();
            long totalTimeSec=(endTime-startTime)/1000;
            txtResult.append("\nTime : "+totalTimeSec+" seconds.");
        } catch (TwitterException ex) {
            txtResult.setText("Please wait "+ex.getRateLimitStatus().getSecondsUntilReset()+" seconds\n");
            Logger.getLogger(AnalyzeTweet.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnAnalyzeActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        Options functions = new Options();
        this.setVisible(false);
        functions.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnalyzeUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnalyzeUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnalyzeUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnalyzeUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnalyzeUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnalyze;
    private javax.swing.JButton btnBack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTweets;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTextArea txtResult;
    private javax.swing.JTextField txtTweets;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
