/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sentimentanalysis;


import java.util.List;
import static sentimentanalysis.Utilities.AnalyzeText;
import static sentimentanalysis.Utilities.CalculateScore;
import static sentimentanalysis.Utilities.ClassifyScore;
import static sentimentanalysis.Utilities.accuracy;
import static sentimentanalysis.Utilities.classification;
import static sentimentanalysis.Utilities.negScore;
import static sentimentanalysis.Utilities.partOfSpeech;
import static sentimentanalysis.Utilities.posScore;
import static sentimentanalysis.Utilities.termDictionary;
import static sentimentanalysis.Utilities.termIds;
import static sentimentanalysis.Utilities.tweetScore;

/**
 *
 * @author Chucho
 */
public class AnalyzeText extends javax.swing.JFrame {

    /**
     * Creates new form AnalyzeText
     */
    public AnalyzeText() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtResultPanel = new javax.swing.JScrollPane();
        txtResult = new javax.swing.JTextArea();
        btnBack = new javax.swing.JButton();
        btnAnalyze = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtResult.setColumns(20);
        txtResult.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        txtResult.setRows(5);
        txtResultPanel.setViewportView(txtResult);

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnAnalyze.setText("Analyze");
        btnAnalyze.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalyzeActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtResultPanel)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 430, Short.MAX_VALUE)
                        .addComponent(btnClear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAnalyze)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtResultPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnAnalyze)
                    .addComponent(btnClear))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        Options functions=new Options();
        this.setVisible(false);
        functions.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAnalyzeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalyzeActionPerformed
        
        long startTime=System.currentTimeMillis();
        termIds=AnalyzeText(txtResult.getText());
        int i=1;
        for (List<Integer> term : termIds)
        {
            txtResult.append("\n"+String.valueOf(i)+".");
            for(Integer id : term){
                txtResult.append("Term "+termDictionary.get(id)+"("+partOfSpeech.get(id)+")" +" found with id '"+id.toString()+"'");
                txtResult.append("\n Positive score : "+posScore.get(id));
                txtResult.append("\n Negative score : "+negScore.get(id));
                txtResult.append("\n Objectivity : "+String.valueOf(1-(posScore.get(id)+negScore.get(id)))+"\n");
            }
            i++;
        }
        
        
        tweetScore=CalculateScore(termIds);
        
        String result=String.valueOf(tweetScore);
        txtResult.append("\n\n Final Score : "+result);
        classification=ClassifyScore(tweetScore);
        txtResult.append("\n Accuracy : "+(accuracy*100)+"%");
        txtResult.append("\n Classification : "+classification);
        long endTime=System.currentTimeMillis();
        long totalTimeSec=(endTime-startTime)/1000;
        txtResult.append("\nTime : "+totalTimeSec+" seconds.");
        
    }//GEN-LAST:event_btnAnalyzeActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        txtResult.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnalyzeText.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnalyzeText.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnalyzeText.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnalyzeText.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnalyzeText().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnalyze;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JTextArea txtResult;
    private javax.swing.JScrollPane txtResultPanel;
    // End of variables declaration//GEN-END:variables
}
