/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sentimentanalysis;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static sentimentanalysis.Utilities.ScanWordNet;
import static sentimentanalysis.Utilities.sentiwordnet;
/**
 *
 * @author Chucho
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        lblTop = new javax.swing.JLabel();
        txtConsumerKey = new javax.swing.JTextField();
        lblConsumerKey = new javax.swing.JLabel();
        lblConsumerSecret = new javax.swing.JLabel();
        lblAccessToken = new javax.swing.JLabel();
        lblAccessTokenKey = new javax.swing.JLabel();
        txtConsumerSecret = new javax.swing.JTextField();
        btnReset = new javax.swing.JButton();
        txtAccessToken = new javax.swing.JTextField();
        txtAccessTokenSecret = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblTop.setText("Enter twitter developer variables");

        txtConsumerKey.setText("qOMHL8L3Sc768j89rZHjnrh0Y");
        txtConsumerKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConsumerKeyActionPerformed(evt);
            }
        });

        lblConsumerKey.setText("Consumer Key :");

        lblConsumerSecret.setText("Consumer Secret :");

        lblAccessToken.setText("Access Token : ");

        lblAccessTokenKey.setText("Access Token Secret : ");

        txtConsumerSecret.setText("RZ0TfojQ0g0X3JoKgPh6k3a42pLgdrXXK8tI0qlsECOESeK7W2");
        txtConsumerSecret.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConsumerSecretActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        txtAccessToken.setText("846697695897116677-7CMAUw1yxqE6JKyILiAjDffxsene6w5");
        txtAccessToken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAccessTokenActionPerformed(evt);
            }
        });

        txtAccessTokenSecret.setText("ho9spkUuagD2udixxbX8JhBiCTASlk1ZNvlUNU5glzpg3");
        txtAccessTokenSecret.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAccessTokenSecretActionPerformed(evt);
            }
        });

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblConsumerSecret, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblAccessToken, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblAccessTokenKey, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(lblConsumerKey))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAccessToken, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                            .addComponent(txtConsumerKey)
                            .addComponent(txtConsumerSecret)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnReset)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSubmit)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtAccessTokenSecret))
                        .addContainerGap())
                    .addComponent(lblTop)))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblAccessToken, lblAccessTokenKey, lblConsumerKey, lblConsumerSecret});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTop)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtConsumerKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblConsumerKey))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtConsumerSecret, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblConsumerSecret))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAccessToken)
                    .addComponent(txtAccessToken, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAccessTokenKey)
                    .addComponent(txtAccessTokenSecret, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReset)
                    .addComponent(btnSubmit))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtConsumerKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConsumerKeyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConsumerKeyActionPerformed

    private void txtConsumerSecretActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConsumerSecretActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConsumerSecretActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        Utilities.ConnectToTwitter(txtConsumerKey.getText(),txtConsumerSecret.getText(),txtAccessToken.getText(),txtAccessTokenSecret.getText());
        JOptionPane.showMessageDialog(null, "Connected to twitter.\nPress OK to scan the Sentiwordnet file");
        //Xreiazomaste to paging gia na paroume parapanw apo 20 apotelesmata
        //h alliws gia na paroume sugkekrimeno ari8mo apo tweets
        Options functions=new Options();
        sentiwordnet = new File("SentiWordNet_3.0.0_20130122.txt");
        try {
            
            ScanWordNet(sentiwordnet);
            JOptionPane.showMessageDialog(null, "SentiWordNet has been scanned");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(AnalyzeTweet.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
        functions.setVisible(true);
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void txtAccessTokenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAccessTokenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAccessTokenActionPerformed

    private void txtAccessTokenSecretActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAccessTokenSecretActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAccessTokenSecretActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        txtConsumerKey.setText("qOMHL8L3Sc768j89rZHjnrh0Y");
        txtConsumerSecret.setText("RZ0TfojQ0g0X3JoKgPh6k3a42pLgdrXXK8tI0qlsECOESeK7W2");
        txtAccessToken.setText("846697695897116677-7CMAUw1yxqE6JKyILiAjDffxsene6w5");
        txtAccessTokenSecret.setText("ho9spkUuagD2udixxbX8JhBiCTASlk1ZNvlUNU5glzpg3");
    }//GEN-LAST:event_btnResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAccessToken;
    private javax.swing.JLabel lblAccessTokenKey;
    private javax.swing.JLabel lblConsumerKey;
    private javax.swing.JLabel lblConsumerSecret;
    private javax.swing.JLabel lblTop;
    private javax.swing.JTextField txtAccessToken;
    private javax.swing.JTextField txtAccessTokenSecret;
    private javax.swing.JTextField txtConsumerKey;
    private javax.swing.JTextField txtConsumerSecret;
    // End of variables declaration//GEN-END:variables
}
